config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  unauthenticated do
    root to: 'pages#home'
  end

  authenticated do
    root to: 'users#dashboard', as: :authenticated_root
  end

  resources :transactions, except: [ :new, :create ]
  resources :pieces do
      resources :transactions, only: [ :new, :create ]
  end
  get 'profil', to: 'users#profil', as: 'profil'
  get 'my_pieces', to: 'pieces#my_pieces', as: 'my_pieces'

  patch 'profil/users_id', to: 'users#update_avatar', as: :update_avatar

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piece.rb
class Piece < ApplicationRecord
  validates :name, presence: true
  has_many :transactions #, dependent: :destroy
  belongs_to :owner , class_name: "User", foreign_key: "user_id"
  has_many_attached :photos
  validates :category, inclusion: { in: %w(peinture sculpture photo autres),
      :message => "%{value} n'est pas une catégorie valide" }

  def unavailable_dates
    transactions.pluck(:date_start, :date_end).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :date_start, presence: true, availability: true
  validates :date_end, presence: true, availability: true
  validates :status, inclusion: { in: %w(demande acceptee annulee),
      :message => "%{value} n'est pas un status valide" }
  validate :end_date_after_start_date
  belongs_to :user
  belongs_to :piece


  private

  def end_date_after_start_date
    return if date_end.blank? || date_start.blank?
    
    if date_end < date_start
      errors.add(date_end, "doit être après la date de début")
    end
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pieces
  has_many :transactions
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @pieces =  Piece.order('created_at DESC').limit(6)
  end
end

app/controllers/pieces_controller.rb
require "open-uri"

class PiecesController < ApplicationController
  before_action :set_piece, only: [:show, :edit, :update, :destroy]

  def create
    new_params = piece_params.except(:wikiphoto)
    @piece = Piece.new(new_params)
    @piece.owner = current_user
    if @piece.save
      attach_remote_photo if piece_params[:wikiphoto]
      redirect_to piece_path(@piece)
    else
      render :new
    end
  end

  def destroy
    @piece.destroy
    redirect_to pieces_path
  end

  def edit
  end

  def index
    @pieces = Piece.all
  end

  def new
    @piece = Piece.new
    @user = current_user
  end

  def show
    set_piece
  end

  def update
    @piece.update(piece_params)
    redirect_to piece_path(@piece)
  end

  def my_pieces
    @pieces = current_user.pieces
    render :index
  end

  private

  def set_piece
    @piece = Piece.find(params[:id])
  end

  def piece_params
    params.require(:piece).permit(:name, :artist, :category, :price, :wikiphoto, photos: [])
  end

  def attach_remote_photo
    wiki_img = URI.open(params[:piece][:wikiphoto].to_s)
    @piece.photos.attach(io: wiki_img, filename: 'wikipedia.jpg', content_type: 'image/jpg')
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def create
    @transaction = Transaction.new(transaction_params)
    @piece = Piece.find(params[:piece_id])
    @transaction.piece = @piece
    @transaction.user = current_user
    if @transaction.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @transaction.destroy
    redirect_to root_path
  end

  def edit
  end

  def index
    @transactions = current_user.transactions.all
    @total = 0
    current_user.transactions.all.each do |t|
       @total += t.piece.price
       p @total
    end
  end

  def new
    @transaction = Transaction.new
    @piece = Piece.find(params[:piece_id])
  end

  def show
  end

  def update
    @transaction.update(transaction_params)
    redirect_to root_path
  end

  private

  def transaction_params
    params.require(:transaction).permit(:date_start, :date_end, :piece_id, :status)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
    @piece = @transaction.piece
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    @transactions = current_user.transactions.all
    @total = 0
    current_user.transactions.all.each do |t|
       @total += (t.date_end - t.date_start).to_i * t.piece.price
       p @total
    end

    @pieces =  Piece.order('created_at DESC').limit(100)
  end

  def profil
  end

  def update_avatar
  current_user.update(profil_params)
  redirect_to profil_path
  end

  private
  def profil_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
  def profile_image(user, opts = {})
    if user.avatar.attached?
      cl_image_tag user.avatar.key, opts
    else
      image_tag "placeholder.jpg", opts
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Art2heart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="my-container">
    <%= yield %>
    </div>




<%= render 'shared/footer' %>



  </body>
</html>

app/views/pages/home.html.erb
<div id="home-entete">

  <h3 id="home-title"></h3>
</div>
<div>
  <%= render 'shared/grille' , pieces: @pieces%>
</div>

app/views/pieces/_form.html.erb
<div class="form-container">
  <%= simple_form_for(@piece) do |f| %>
  <%= f.input :name %>
  <%= f.input :artist %>
  <%= f.select :category, collection: %w(peinture sculpture photo autres) %>
  <%= f.input :price %>
  <%= f.input :photos, hint: "Votre oeuvre", label:'Selectionner vos photo', as: :file, input_html: { multiple: true, accept: "image/*" }%>
  <p>ou alors</p>
  <%= link_to "rechercher sur Wikipedia", "#", id: "wikiBtn", class: "btn btn-ghost btn-lg btn-block btn-booking", remote: :true %>
  <br>
  <div id="wikiImg"></div>
  <%= link_to "", class: "hidden btn btn-ghost btn-lg btn-block btn-booking", id: "btnPhoto", remote: :true do %>
     Ajouter <i class="fas fa-plus-circle"></i>
  <% end %>
  <br>
  <%= f.submit "Valider", class: "btn btn-ghost btn-lg btn-block btn-booking" %>
<% end %>
<br>
</div>



<%= javascript_pack_tag 'wikiImage' %>

app/views/pieces/edit.html.erb
<%= render "form", piece: @piece %>
<%= link_to "annuler", piece_path(@piece), class: "btn btn-ghost" %>

app/views/pieces/index.html.erb
<div>
  <%= render 'shared/grille' , pieces: @pieces%>
</div>

app/views/pieces/new.html.erb
<%= render "form", piece: @piece %>
<%= link_to "annuler", root_path , class: "btn btn-ghost"%>

app/views/pieces/show.html.erb
<div class="show-container">

  <div class="show-image">
    <%= render 'shared/carousel', piece: @piece %>
    <div class="show-image-wiki">
      <p id="wikipedia"></p>
    </div>
  </div>


  <div class="show-info">
    <div class="info-piece">
      <h1 id="piece-name"><%= @piece.name %></h1>
      <h2>Artiste : <%= @piece.artist %></h2>
      <h2>Propriétaire : <%= @piece.owner.first_name %> <%= @piece.owner.last_name %></h2>
      <h2>Prix par journée de location : <%= @piece.price %> €</h2>
    </div>
  </div>

  <div class="flex flex-inline mt-5">

    <%= link_to "Retour", root_path, class: "btn btn-ghost" %>
    <% if user_signed_in?  %>
      <%= link_to "Réserver", new_piece_transaction_path(@piece) ,class: "btn btn-ghost" %>
      <% if current_user == @piece.owner %>
        <%= link_to 'modifier', edit_piece_path(@piece) ,class: "btn btn-ghost" %>
        <%= link_to piece_path(@piece),
                    method: :delete,
                    data: { confirm: "Voulez-vous supprimer #{@piece.name}?" },
                    type: "button",
                    class: "btn btn-ghost" do %>
          Supprimer
        <% end %>
      <% end %>
    <% end %>


  </div>

</div>

<%= javascript_pack_tag 'wikiText' %>

app/views/shared/_carousel.html.erb
<div class="pieces">

  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% if piece.photos.count > 1 %>
        <% piece.photos.each_with_index  do |photo, i| %>
          <% if i.zero? %>
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <% else %>
            <li data-target="#carouselExampleCaptions" data-slide-to=<%= i %>></li>
          <% end %>
        <% end %>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% piece.photos.each_with_index  do |photo, i| %>
        <% if i.zero? %>
          <div class="carousel-item active">
        <% else %>
          <div class="carousel-item">
        <% end %>
            <%= cl_image_tag photo.key ,width: 600, height: 600, crop: :fill , gravity: :face, class: "d-block w-100" %>
          </div>
        <%end %>
      </div>

      <% if piece.photos.count > 1 %>

        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Précedent</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Suivant</span>
        </a>
      <% end %>
    </div>


  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/francois0690/art2heart"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Toute l'équipe d'Art2Hearth vous remercie de votre visite et de votre patience <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_grille.html.erb
<div class="grille">
    <% if user_signed_in?  %>

          <% if current_user.pieces == pieces %>

            <h1>Mes oeuvres
              <%= link_to new_piece_path do %>
                  <i class="fas fa-plus-circle"></i>
              <% end %>
            </h1>
              <% if current_user.pieces.count == 0 %>

                <h3>Vous n'avez pas encore ajouté d'oeuvre à votre collection</h3>
              <% else %>
                <h3>Vous avez <%= current_user.pieces.count %> oeuvres dans votre collection</h3>
              <% end %>
          <% else %>
            <h1>Les dernières oeuvres en magasin</h1>
          <% end %>

    <% else %>
      <h1>Les dernières oeuvres en magasin</h1>
    <% end %>
    <div class="oeuvres">
        <% pieces.each do |p| %>
          <%= link_to piece_path(p) do %>
            <div class="oeuvre" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path p.photos.first.key ,height: 350, width: 350, crop: :fill, gravity: :face %>)">
              <h2><%= p.name %></h2>
              <p><i><%= p.artist%></i></p>
              <h3>Louez-moi à partir de <%= p.price %> €/jour</h3>
            </div>
          <% end %>
        <% end %>
    </div>

</div>

app/views/shared/_logo.html.erb
  <%= link_to root_path do %>
  <div class="logo">
    <%= image_tag "art2heart.png",  width: '140' %>
    <p class="logo-baseline ">la location d'oeuvres d'art 3.0</p>
  </div>
  <% end %>

app/views/shared/_navbar.html.erb
<%= render 'shared/logo' , pieces: @pieces%>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Catalogue", pieces_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown ">
          <%= profile_image(current_user, class: "avatar dropdown-toggle nav-item", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mes oeuvres", my_pieces_path, class: "dropdown-item" %>
            <%= link_to "Mes réservations", transactions_path, class: "dropdown-item" %>
            <%= link_to "Profil", profil_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_transactions.html.erb
<div class="gauche">

    <div class="transactions">
      <h1>Mes réservations</h1>
      <% if current_user.transactions.count == 0 %>
        <h3><%= current_user.first_name %>, vous n'avez pas encore effectué de réservations</h3>
      <% else %>
        <h3><%= current_user.first_name %>, vous avez effectué de <%= current_user.transactions.count %> réservations</h3>

        <% @transactions.each do |t| %>

          <%= link_to transaction_path(t) do %>

              <div class="transaction" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path t.piece.photos.first.key, width: 500, height: 300, crop: :fill, gravity: :face %>)">
                  <div class="card-trip-infos">

                      <h2><%= t.piece.name.upcase %> <i>(<%= t.piece.artist%>)</i></h2>
                      <% if (t.date_end - t.date_start).to_i > 1 %>
                        <p>Durée de la location: <%= (t.date_end - t.date_start).to_i %> jours</p>
                      <% else %>
                        <p>Durée de la location: <%= (t.date_end - t.date_start).to_i %> jour</p>
                      <% end %>
                      <p>Type d'oeuvre: <%= t.piece.category%></p>
                      <p>Propriétaire : <%= t.piece.owner.first_name %> <%= t.piece.owner.last_name %></p>


                    <%= profile_image(t.piece.owner, class: "card-trip-user avatar-bordered",width: 40, height: 40, crop: :fill , gravity: :face) %>
                        <div class="card-trip-pricing">
                          <%= link_to edit_transaction_path(t), id: "edit" do %>
                           <i class="far fa-edit"></i>
                           <% end %>

                          <%= link_to transaction_path(t),
                            id: "delete",
                            method: :delete,
                            data: { confirm: "Voulez-vous annuler la réservation de :#{t.piece.name}?" } do %>
                            <i class="fas fa-trash"></i>
                            <% end %>

                          <h2>  <%= (t.date_end - t.date_start).to_i * t.piece.price %> €</h2>
                        </div>
                  </div>
              </div>
          <% end %>
        <% end %>
    </div>

    <div class="droite">
      <h3>Total de vos réservations</h3>

        <% @transactions.each_with_index do |t,i| %>
          <p>Réservation <%= i+1 %> : <%= (t.date_end - t.date_start).to_i * t.piece.price%> €</p>
        <% end %>

      <p id="ht">Montant total : <%= @total.round(2) %> €</p>
    </div>

      <% end %>
</div>

app/views/transactions/_form.html.erb
<div class="form-container">
  <div id='piece-booking-dates' data-unavailable="<%= @piece.unavailable_dates.to_json %>">
    <%= simple_form_for([@piece, @transaction]) do |f| %>
      <%= f.input :date_start, as: :string, label: "Dates", placeholder: "à partir de", wrapper_html: {  class: "inline_field_wrapper" } %>
      <%= f.input :date_end, as: :string, label: '&nbsp;'.html_safe, placeholder: "jusqu'à", disabled: true, wrapper_html: { class: "inline_field_wrapper" } %>
      <%= f.submit "reserver", class: "btn btn-ghost btn-lg btn-block btn-booking" %>
    <% end %>
   </div>
</div>

app/views/transactions/edit.html.erb
<div id='piece-booking-dates' data-unavailable="<%= @transaction.piece.unavailable_dates.to_json %>">
  <%= simple_form_for([@transaction]) do |f| %>
      <div class="form-container">
        <%= f.input :date_start, as: :string, label: "Dates", placeholder: "à partir de", wrapper_html: {  class: "inline_field_wrapper" } %>
        <%= f.input :date_end, as: :string, label: '&nbsp;'.html_safe, placeholder: "jusqu'à", disabled: true, wrapper_html: { class: "inline_field_wrapper" } %>
        <%= f.submit "reserver", class: "btn btn-ghost btn-lg btn-block btn-booking" %>
      </div>
  <% end %>
</div>

<div class="flex d-flex justify-content-center mt-5 ">
<%= link_to "annuler", transaction_path(@transaction), class: "btn btn-lg btn-ghost" %>
</div>

app/views/transactions/index.html.erb
<div class="container">
  <%= render 'shared/transactions' %>
</div>

app/views/transactions/new.html.erb
<h2>pièce : <%= @piece.name %></h2>
<p>propriétaire : <%= "#{@piece.owner.first_name} #{@piece.owner.last_name}"%></p>
  <%= render "form", transaction: @transaction, piece: @piece %>
<br>


<div class="flex d-flex justify-content-center mt-5 ">
<%= link_to "retour", piece_path(@piece), class: "btn btn-lg btn-ghost" %>
</div>

app/views/transactions/show.html.erb
<div class="show-transaction">




  <%= render 'shared/carousel', piece: @transaction.piece %>



<div class="show-info">
    <div class="info-piece">
      <h1 id="piece-name"><%= @piece.name %></h1>
      <h2>Artiste : <%= @piece.artist %></h2>
      <h2>Propriétaire : <%= @piece.owner.first_name %> <%= @piece.owner.last_name %></h2>
      <h2><%= "Début de location : #{@transaction.date_start}" %></h2>
      <h2><%= "Fin de location : #{@transaction.date_end}" %></h2>
          <h2>Montant de la location : <%= (@transaction.date_end - @transaction.date_start).to_i * @transaction.piece.price %> € </h2>

    </div>
  </div>




  <div class= "d-inline-flex ">
  <%= button_to "Retour aux réservations", transactions_path, method: :get, class: "btn btn-ghost" %>
  <%= button_to 'Modifier', edit_transaction_path(@transaction), method: :get,class: "btn btn-ghost"%>

  <%= button_to 'Annuler la réservation', transaction_path(@transaction),
          method: :delete,
          data: { confirm: "Voulez-vous annuler la réservation de :#{@transaction.piece.name}?" },
          class: "btn btn-ghost" %>
  </div>


</div>

app/views/users/dashboard.html.erb
<ul class="nav-light nav nav-pills my-4" id="dashboard" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="resa-tab" data-toggle="tab" href="#resa" role="tab" aria-controls="resa" aria-selected="true">Mes réservations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="oeuvres-tab" data-toggle="tab" href="#oeuvres" role="tab" aria-controls="oeuvres" aria-selected="false">Mes oeuvres</a>
  </li>
</ul>
<div class="tab-content " id="dashboardContent">
  <div class="tab-pane fade show active" id="resa" role="tabpanel" aria-labelledby="resa-tab"> <%= render 'shared/transactions' %> </div>
  <div class="tab-pane fade" id="oeuvres" role="tabpanel" aria-labelledby="oeuvres-tab"><%= render 'shared/grille' , pieces: current_user.pieces%></div>
</div>


<div class="mt-4">
  <%= render 'shared/grille' , pieces: @pieces%>
</div>

app/views/users/profil.html.erb
<div class="flex d-flex justify-content-center mt-3 ">
  <%= profile_image(current_user) %>
</div>

<%= simple_form_for(current_user, :url => update_avatar_path, method: 'patch' ) do |f| %>
  <div class="form-container">
      <%= f.input :first_name,
                    required: true,
                    autofocus: true,
                    label:'Prénom',
                    input_html: { autocomplete: "prénom" }%>
      <%= f.input :last_name,
                    required: true,
                    autofocus: true,
                    label:'Nom',
                    input_html: { autocomplete: "nom" }%>
      <%= f.input :avatar,
                    label:'Selectionner une photo',
                    as: :file, input_html: { accept: "image/*" }%>
      <%= f.submit%>
  </div>
<% end %>
<div class="flex d-flex justify-content-center mt-3 ">
  <%= link_to "changer mot de passe", edit_user_registration_path, class: "btn btn-ghost" %>
  <%= link_to "retour au dashboard", root_path , class: "btn btn-ghost"%>
</div>